apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp #name of pod grou[
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue #name of pod grou[
spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1
